export const DRUPAL_STATE_NAME = 'drupal'

// DRUPAL_REQUEST_NODE
export const DRUPAL_REQUEST_NODE = '@drupal/REQUEST_NODE'
export const DRUPAL_REQUEST_NODE_SUCCESS = '@drupal/REQUEST_NODE_SUCCESS'

// DRUPAL_REQUEST_MENU
export const DRUPAL_REQUEST_MENU = '@drupal/REQUEST_MENU'
export const DRUPAL_REQUEST_MENU_SUCCESS = '@drupal/REQUEST_MENU_SUCCESS'

// DRUPAL_REQUEST_FAQ
export const DRUPAL_REQUEST_FAQ = '@drupal/REQUEST_FAQ'
export const DRUPAL_REQUEST_FAQ_SUCCESS = '@drupal/REQUEST_FAQ_SUCCESS'
