export const COOKIE_STORE_NAME = 'cookiePolicy'

export const REQUEST_COOKIE_POLICY = 'app/COOKIE/REQUEST_COOKIE_POLICY'
export const REQUEST_COOKIE_POLICY_SUCCESS = 'app/COOKIE/REQUEST_COOKIE_POLICY_SUCCESS'
