export const PAYMENT_STORE_NAME = 'payment'

export const REQUEST_PAYMENT_CONFIG = 'app/src/Payment/REQUEST_PAYMENT_CONFIG'
export const REQUEST_PAYMENT_CONFIG_SUCCESS = 'app/src/Payment/REQUEST_PAYMENT_CONFIG_SUCCESS'
export const REQUEST_PAYMENT_CONFIG_ERROR = 'app/src/Payment/REQUEST_PAYMENT_CONFIG_ERROR'

export const REQUEST_PAYMENT_CONFIRMATION = 'app/src/Payment/REQUEST_PAYMENT_CONFIRMATION'
export const REQUEST_PAYMENT_CONFIRMATION_SUCCESS = 'app/src/Payment/REQUEST_PAYMENT_CONFIRMATION_SUCCESS'
export const REQUEST_PAYMENT_CONFIRMATION_ERROR = 'app/src/Payment/REQUEST_PAYMENT_CONFIRMATION_ERROR'

export const BACK_FROM_ADYEN = 'app/src/Payment/BACK_FROM_ADYEN'

export const REQUEST_BOOKING_PROCESS = 'app/src/Payment/REQUEST_BOOKING_PROCESS'
export const REQUEST_BOOKING_PROCESS_SUCCESS = 'app/src/Payment/REQUEST_BOOKING_PROCESS_SUCCESS'
export const REQUEST_BOOKING_PROCESS_ERROR = 'app/src/Payment/REQUEST_BOOKING_PROCESS_ERROR'
