export const ROOM_STORE_NAME = 'rooms'

// AVAILABILITIES
export const REQUEST_ROOMS_AVAILABILITIES = 'app/src/Rooms/REQUEST_ROOMS_AVAILABILITIES'
export const REQUEST_ROOMS_AVAILABILITIES_SUCCESS = 'app/src/Rooms/REQUEST_ROOMS_AVAILABILITIES_SUCCESS'
export const REQUEST_ROOMS_AVAILABILITIES_ERROR = 'app/src/Rooms/REQUEST_ROOMS_AVAILABILITIES_ERROR'

// FEATURES
export const REQUEST_ROOMS_FEATURES = 'app/src/Rooms/REQUEST_ROOMS_FEATURES'
export const REQUEST_ROOMS_FEATURES_SUCCESS = 'app/src/Rooms/REQUEST_ROOMS_FEATURES_SUCCESS'
export const REQUEST_ROOMS_FEATURES_ERROR = 'app/src/Rooms/REQUEST_ROOMS_FEATURES_ERROR'

// GALLERY
export const REQUEST_ROOMS_GALLERY = 'app/src/Rooms/REQUEST_ROOMS_GALLERY'
export const REQUEST_ROOMS_GALLERY_SUCCESS = 'app/src/Rooms/REQUEST_ROOMS_GALLERY_SUCCESS'
export const REQUEST_ROOMS_GALLERY_ERROR = 'app/src/Rooms/REQUEST_ROOMS_GALLERY_ERROR'
