export const BRAND_STORE_NAME = 'brand'

// REQUEST_PARTNERS
export const REQUEST_PARTNERSHIP = '@partnership/REQUEST_PARTNERSHIP'
export const REQUEST_PARTNERSHIP_SUCCESS = '@partnership/REQUEST_PARTNERSHIP_SUCCESS'
