// STORE KEYS
export const HOTEL_STORE_NAME = 'hotels'

// SAGA KEYS
export const HOTEL_SAGA_NAME = 'hotelsSaga'

// AVAILABILITIES
export const REQUEST_HOTEL_AVAILABILITIES = 'app/src/Hotels/REQUEST_HOTEL_AVAILABILITIES'
export const REQUEST_HOTEL_AVAILABILITIES_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_AVAILABILITIES_SUCCESS'
export const REQUEST_HOTEL_AVAILABILITIES_ERROR = 'app/src/Hotels/REQUEST_HOTEL_AVAILABILITIES_ERROR'

export const REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES = 'app/src/Hotels/REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES'
export const REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES_SUCCESS'
export const REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES_ERROR = 'app/src/Hotels/REQUEST_HOTEL_FROM_COORDINATES_AVAILABILITIES_ERROR'

export const REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES = 'app/src/Hotels/REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES'
export const REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES_SUCCESS = 'app/src/Hotels/REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES_SUCCESS'
export const REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES_ERROR = 'app/src/Hotels/REQUEST_ALTERNATIVE_DATES_HOTEL_AVAILABILITIES_ERROR'

export const REQUEST_HOTEL_DETAILS = 'app/src/Hotels/REQUEST_HOTEL_DETAILS'
export const REQUEST_HOTEL_DETAILS_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_DETAILS_SUCCESS'
export const REQUEST_HOTEL_DETAILS_ERROR = 'app/src/Hotels/REQUEST_HOTEL_DETAILS_ERROR'

// COMPARATOR
export const REQUEST_HOTEL_COMPARATOR = 'app/src/Hotels/REQUEST_HOTEL_COMPARATOR'
export const REQUEST_HOTEL_COMPARATOR_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_COMPARATOR_SUCCESS'
export const REQUEST_HOTEL_COMPARATOR_ERROR = 'app/src/Hotels/REQUEST_HOTEL_COMPARATOR_ERROR'

// FEATURES
export const REQUEST_HOTEL_FEATURES = 'app/src/Hotels/REQUEST_HOTEL_FEATURES'
export const REQUEST_HOTEL_FEATURES_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_FEATURES_SUCCESS'
export const REQUEST_HOTEL_FEATURES_ERROR = 'app/src/Hotels/REQUEST_HOTEL_FEATURES_ERROR'

// PACKAGES
export const REQUEST_HOTEL_PACKAGES = 'app/src/Hotels/REQUEST_HOTEL_PACKAGES'
export const REQUEST_HOTEL_PACKAGES_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_PACKAGES_SUCCESS'
export const REQUEST_HOTEL_PACKAGES_ERROR = 'app/src/Hotels/REQUEST_HOTEL_PACKAGES_ERROR'

// SEARCH
export const REQUEST_HOTEL_SEARCH = 'app/src/Hotels/REQUEST_HOTEL_SEARCH'
export const REQUEST_HOTEL_SEARCH_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_SEARCH_SUCCESS'
export const REQUEST_HOTEL_SEARCH_ERROR = 'app/src/Hotels/REQUEST_HOTEL_SEARCH_ERROR'

export const REQUEST_HOTEL_PLACE_SUCCESS = 'app/src/Hotels/REQUEST_HOTEL_PLACE_SUCCESS'
export const REQUEST_HOTEL_PLACE_ERROR = 'app/src/Hotels/REQUEST_HOTEL_PLACE_ERROR'

export const REQUEST_SEARCH_CURRENT_LOCATION = 'app/src/Hotels/REQUEST_SEARCH_CURRENT_LOCATION'
export const REQUEST_SEARCH_CURRENT_LOCATION_SUCCESS = 'app/src/Hotels/REQUEST_SEARCH_CURRENT_LOCATION_SUCCESS'
export const REQUEST_SEARCH_CURRENT_LOCATION_ERROR = 'app/src/Hotels/REQUEST_SEARCH_CURRENT_LOCATION_ERROR'

export const REQUEST_GEOLOC_SEARCH = 'app/src/Hotels/REQUEST_GEOLOC_SEARCH'
export const REQUEST_GEOLOC_SEARCH_SUCCESS = 'app/src/Hotels/REQUEST_GEOLOC_SEARCH_SUCCESS'
export const REQUEST_GEOLOC_SEARCH_ERROR = 'app/src/Hotels/REQUEST_GEOLOC_SEARCH_ERROR'

export const SET_QUERY_SEARCH = 'app/src/Hotels/SET_QUERY_SEARCH'

// RATE plans
export const RATE_PLAN_VISIBILITY_DEFAULT = 'DEFAULT'
